apiVersion: v1
kind: Service
metadata:
  name: car-rental-frontend-service
  namespace: car-rental
spec:
  type: NodePort
  selector:
    app: car-rental-frontend
  ports:
    - protocol: TCP
      port: 80          # Port interne du service
      targetPort: 80    # Port du container (NGINX)
      nodePort: 32080 
