apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: car-rental
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: rakizouari/api-gateway:latest
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server.car-rental.svc.cluster.local:8761/eureka/
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: car-rental
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80        
      targetPort: 8081 
      protocol: TCP
      nodePort: 32326
  type: NodePort      
