apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: car-rental
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: rakizouari/userservice:latest
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.car-rental.svc.cluster.local:3306/carrental
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server.car-rental.svc.cluster.local:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: car-rental
spec:
  selector:
    app: user-service
  ports:
    - port: 8089
      targetPort: 8089
  type: ClusterIP
